services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "1010:80"
    volumes:
      - ./:/www
      - ./priv/config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: .
    container_name: php-fpm
    volumes:
      - ./:/www

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: deno_dev
    volumes:
      - ./priv/data/cache/docker/database:/var/lib/postgresql/data
      - ./priv/data/database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - 1111:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 1212:8080
