services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "1010:80"
    volumes:
      - ./:/www
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:8.3-fpm
    container_name: php-fpm
    volumes:
      - ./:/www