FROM node:16

USER root

COPY ../../../ ./deno

WORKDIR /deno/priv

CMD chmod -R 777 /deno && npm install && npx tailwindcss -i /deno/public/assets/styles/global.css -o /deno/public/assets/styles/tailwind.css --watch
